cors:
  originPatterns: http://localhost:3000,http://localhost:8080,https://com.example
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest_spring?useTimezone=True&serverTimezone=UTC
    username: root
    password: Alex#1985
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
spring-doc:
  paths-to-match:
    - /api/**/v1/**
  swagger-ui:
    use-root-path: true
