spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest_spring?useTimezone=True&serverTimezone=UTC
    username: root
    password: Alex#1985
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false